schema_version = 1
distribution = "wilfred-public-alpha"
channel = "0.2.0-dev"

[components.butler_core]
package = "butler-core"
version = "0.1.3"

[components.wilfred]
package = "wilfred-butler"
version = "0.2.0"

[components.home_assistant]
package = "wilfred-home-assistant"
version = "0.1.0.dev0"
git_ref = "60882a1efba3c3a248047ff69c8ca83352263da7"
